### ISSUE TITLE
Boundary condition and Mesh Independence 

### ISSUE THREAD

**Issue by ansabsindhu** [unicfdlab/TrainingTracks#17]
Hello,
Hope you are doing fine. I will really appreciate if you can address the below queries.
I tried to run the case (TrainingTracks-master/OpenFOAM/simpleFsi-OFv1812/cases/test-laminar-cont) on a coarse mesh to visualize the mesh motion but the simulation failed to converge.
I wish to implement symmetry condition instead of the channel and the simulation gave an error. 

Can you please comment on the above errors. Apart from that, please recommend any supplement material to study.

Regards,
Ali

**Comment by unicfdlab** [comment]
Hi, can you be more specific on the issues you mentioned:
- where did you get the coarse mesh for the simulation? Is it the original mesh located in TrainingTracks-master/OpenFOAM/simpleFsi-OFv1812/cases/test-laminar-cont/constant/polyMesh?
- does the simulation diverge immediately after the start or it takes some time (how much?) to reach the diverging state?
- what symmetry condition instead of the channel condition are you talking about? Do you want to impose slip condition on top and bottom walls of the channel? Or you need something more complicated?
- please, attach logs & graphic materials to your reply, if you have any.

**Comment by unicfdlab** [comment]
I checked the original case "TrainingTracks-master/OpenFOAM/simpleFsi-OFv1812/cases/test-laminar-cont/" and it works well
